server:
  port: 10086

spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

# sl4j 打印相关配置
logging:
  file:
    path: /log-tailf

log-config:
  # 第一次进入页面默认获取的日志行数
  default-show-line-num: 100

  # 监听目录，可以设置多个以 ; 隔开
  monitor-path : d:/log;d:/log2

